/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/slayer321/crdcreation/pkg/apis/sachinmaurya.tech/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHADeployments implements HADeploymentInterface
type FakeHADeployments struct {
	Fake *FakeSachinmauryaV1alpha1
	ns   string
}

var hadeploymentsResource = schema.GroupVersionResource{Group: "sachinmaurya.tech", Version: "v1alpha1", Resource: "hadeployments"}

var hadeploymentsKind = schema.GroupVersionKind{Group: "sachinmaurya.tech", Version: "v1alpha1", Kind: "HADeployment"}

// Get takes name of the hADeployment, and returns the corresponding hADeployment object, and an error if there is any.
func (c *FakeHADeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HADeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hadeploymentsResource, c.ns, name), &v1alpha1.HADeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HADeployment), err
}

// List takes label and field selectors, and returns the list of HADeployments that match those selectors.
func (c *FakeHADeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HADeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hadeploymentsResource, hadeploymentsKind, c.ns, opts), &v1alpha1.HADeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HADeploymentList{ListMeta: obj.(*v1alpha1.HADeploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.HADeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hADeployments.
func (c *FakeHADeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hadeploymentsResource, c.ns, opts))

}

// Create takes the representation of a hADeployment and creates it.  Returns the server's representation of the hADeployment, and an error, if there is any.
func (c *FakeHADeployments) Create(ctx context.Context, hADeployment *v1alpha1.HADeployment, opts v1.CreateOptions) (result *v1alpha1.HADeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hadeploymentsResource, c.ns, hADeployment), &v1alpha1.HADeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HADeployment), err
}

// Update takes the representation of a hADeployment and updates it. Returns the server's representation of the hADeployment, and an error, if there is any.
func (c *FakeHADeployments) Update(ctx context.Context, hADeployment *v1alpha1.HADeployment, opts v1.UpdateOptions) (result *v1alpha1.HADeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hadeploymentsResource, c.ns, hADeployment), &v1alpha1.HADeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HADeployment), err
}

// Delete takes name of the hADeployment and deletes it. Returns an error if one occurs.
func (c *FakeHADeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hadeploymentsResource, c.ns, name), &v1alpha1.HADeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHADeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hadeploymentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HADeploymentList{})
	return err
}

// Patch applies the patch and returns the patched hADeployment.
func (c *FakeHADeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HADeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hadeploymentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HADeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HADeployment), err
}
