/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/slayer321/crdcreation/pkg/apis/sachinmaurya.tech/v1alpha1"
	scheme "github.com/slayer321/crdcreation/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HADeploymentsGetter has a method to return a HADeploymentInterface.
// A group's client should implement this interface.
type HADeploymentsGetter interface {
	HADeployments(namespace string) HADeploymentInterface
}

// HADeploymentInterface has methods to work with HADeployment resources.
type HADeploymentInterface interface {
	Create(ctx context.Context, hADeployment *v1alpha1.HADeployment, opts v1.CreateOptions) (*v1alpha1.HADeployment, error)
	Update(ctx context.Context, hADeployment *v1alpha1.HADeployment, opts v1.UpdateOptions) (*v1alpha1.HADeployment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HADeployment, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HADeploymentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HADeployment, err error)
	HADeploymentExpansion
}

// hADeployments implements HADeploymentInterface
type hADeployments struct {
	client rest.Interface
	ns     string
}

// newHADeployments returns a HADeployments
func newHADeployments(c *SachinmauryaV1alpha1Client, namespace string) *hADeployments {
	return &hADeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hADeployment, and returns the corresponding hADeployment object, and an error if there is any.
func (c *hADeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HADeployment, err error) {
	result = &v1alpha1.HADeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hadeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HADeployments that match those selectors.
func (c *hADeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HADeploymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HADeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hadeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hADeployments.
func (c *hADeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hadeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hADeployment and creates it.  Returns the server's representation of the hADeployment, and an error, if there is any.
func (c *hADeployments) Create(ctx context.Context, hADeployment *v1alpha1.HADeployment, opts v1.CreateOptions) (result *v1alpha1.HADeployment, err error) {
	result = &v1alpha1.HADeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hadeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hADeployment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hADeployment and updates it. Returns the server's representation of the hADeployment, and an error, if there is any.
func (c *hADeployments) Update(ctx context.Context, hADeployment *v1alpha1.HADeployment, opts v1.UpdateOptions) (result *v1alpha1.HADeployment, err error) {
	result = &v1alpha1.HADeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hadeployments").
		Name(hADeployment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hADeployment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hADeployment and deletes it. Returns an error if one occurs.
func (c *hADeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hadeployments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hADeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hadeployments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hADeployment.
func (c *hADeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HADeployment, err error) {
	result = &v1alpha1.HADeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hadeployments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
